FROM --platform=linux/arm64 public.ecr.aws/amazonlinux/amazonlinux:2023

WORKDIR /app

RUN dnf install -y \
    ruby rubygems ruby-devel gcc make \
    lsof net-tools procps-ng htop iproute iputils \
    vim-enhanced nano wget unzip file \
    && dnf clean all

RUN gem install bundler --no-document
RUN GEM_HOME=/dd_tracer/ruby gem install datadog --no-document

COPY app.rb Gemfile ./

COPY serverless-init-linux-arm64 /serverless-init
RUN chmod +x /serverless-init

EXPOSE 8080
EXPOSE 9000

ENV AWS_LAMBDA_MICROVM_IMAGE_ARN=arn:aws:lambda:us-east-1:123456789012:microvm:sample-ruby-app
ENV AWS_LAMBDA_FUNCTION_NAME=sample-ruby-app
ENV DD_SITE=datadoghq.com
ENV DD_SERVICE=sample-ruby-app
ENV DD_VERSION=1
ENV DD_ENV=devmicrovm
ENV DD_LOGS_ENABLED=true
ENV DD_LOG_LEVEL=debug
ENV DD_TRACE_SAMPLE_RATE=1.0
ENV DD_LOGS_INJECTION=true
ENV DD_TRACE_ENABLED=true
ENV DD_TRACE_AGENT_URL=http://localhost:8126
ENV DD_TRACE_STARTUP_LOGS=true
ENV DD_TRACE_DEBUG=true
ENV DD_SERVERLESS_MICROVM_USER_APP_PORT=8080
ENV GEM_PATH=/dd_tracer/ruby

ENTRYPOINT ["/serverless-init"]
CMD ["ruby", "app.rb"]
